reload_integration:
  name: "Reload integration"
  description: "Reloading the integration."
  fields:
    dummy_field:
      name: "Dummy Field"
      description: "A placeholder field for reloading the integration."

check_for_updates:
  name: "Check for Updates"
  description: "Manually check for firmware updates on all dongles"
  fields: {}
